//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 07/07/2020 17:21:06
namespace Microsoft.Dynamics.CRM
{
    /// <summary>
    /// There are no comments for crmbaseentitySingle in the schema.
    /// </summary>
    public partial class crmbaseentitySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<crmbaseentity>
    {
        /// <summary>
        /// Initialize a new crmbaseentitySingle object.
        /// </summary>
        public crmbaseentitySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new crmbaseentitySingle object.
        /// </summary>
        public crmbaseentitySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new crmbaseentitySingle object.
        /// </summary>
        public crmbaseentitySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<crmbaseentity> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for crmbaseentity in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.EntityType()]
    public abstract partial class crmbaseentity : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
