//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 07/07/2020 17:21:06
namespace Microsoft.Dynamics.CRM
{
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Microsoft.Dynamics.CRM.account as global::Microsoft.Dynamics.CRM.accountSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.Dynamics.CRM.accountSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.account> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::Microsoft.Dynamics.CRM.accountSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.Dynamics.CRM.account as global::Microsoft.Dynamics.CRM.accountSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="accountid">The value of accountid</param>
        public static global::Microsoft.Dynamics.CRM.accountSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.account> source,
            global::System.Nullable<global::System.Guid> accountid)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "accountid", accountid }
            };
            return new global::Microsoft.Dynamics.CRM.accountSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Cast an entity of type global::Microsoft.Dynamics.CRM.crmbaseentity to its derived type global::Microsoft.Dynamics.CRM.account
        /// </summary>
        /// <param name="source">source entity</param>
        public static global::Microsoft.Dynamics.CRM.accountSingle CastToaccount(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.Dynamics.CRM.crmbaseentity> source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.Dynamics.CRM.account> query = source.CastTo<global::Microsoft.Dynamics.CRM.account>();
            return new global::Microsoft.Dynamics.CRM.accountSingle(source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.Dynamics.CRM.contact as global::Microsoft.Dynamics.CRM.contactSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.Dynamics.CRM.contactSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.contact> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::Microsoft.Dynamics.CRM.contactSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.Dynamics.CRM.contact as global::Microsoft.Dynamics.CRM.contactSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="contactid">The value of contactid</param>
        public static global::Microsoft.Dynamics.CRM.contactSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.Dynamics.CRM.contact> source,
            global::System.Nullable<global::System.Guid> contactid)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "contactid", contactid }
            };
            return new global::Microsoft.Dynamics.CRM.contactSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Cast an entity of type global::Microsoft.Dynamics.CRM.crmbaseentity to its derived type global::Microsoft.Dynamics.CRM.contact
        /// </summary>
        /// <param name="source">source entity</param>
        public static global::Microsoft.Dynamics.CRM.contactSingle CastTocontact(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.Dynamics.CRM.crmbaseentity> source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.Dynamics.CRM.contact> query = source.CastTo<global::Microsoft.Dynamics.CRM.contact>();
            return new global::Microsoft.Dynamics.CRM.contactSingle(source.Context, query.GetPath(null));
        }
    }
}
